delete feature
pingcap/tispark pull request #2276
Opened 2022-03-24 08:59 UTC by shiyuhang0

### What problem does this PR solve? 
https://github.com/pingcap/tispark/issues/2235

2022-03-24 09:39 UTC, shiyuhang0 commented
/run-all-test

2022-03-24 10:40 UTC, shiyuhang0 commented
/run-all-tests

2022-03-24 10:40 UTC, shiyuhang0 commented
@xuanyu66 @birdstorm PTAL

2022-03-25 04:40 UTC, shiyuhang0 commented
/run-all-tests

2022-03-25 07:14 UTC, shiyuhang0 commented
/run-all-tests

2022-03-25 07:22 UTC, shiyuhang0 commented
/run-all-tests

2022-03-25 08:15 UTC, shiyuhang0 commented
/run-all-tests

2022-03-25 08:56 UTC, shiyuhang0 commented
/run-all-tests

2022-03-25 09:00 UTC, shiyuhang0 commented
/run-all-tests

2022-03-25 09:05 UTC, shiyuhang0 commented
/run-all-tests

2022-03-28 06:59 UTC, shiyuhang0 commented
/run-all-tests

2022-03-29 10:58 UTC, xuanyu66 requested changes

2022-03-29 10:58 UTC, xuanyu66 commented on README.md
> +### Get TiDB Version
<img width="421" alt="image" src="https://user-images.githubusercontent.com/17768378/160594999-0a659585-ff8f-438c-9f5f-8adc4d10a9b2.png">
It’s TiSpark's version

2022-03-29 10:58 UTC, xuanyu66 commented on README.md
> +spark.sql("select ti_version()").show
use collect, not show

2022-03-29 10:58 UTC, xuanyu66 commented on README.md
> +### Delete with TiSpark
Note with only support with version 2.6.x

2022-03-29 10:58 UTC, xuanyu66 commented on core/src/main/scala/com/pingcap/tispark/utils/TwoPhaseCommitHepler.scala
> +      new TiDBOptions(
Extract these options into a class

2022-03-29 11:00 UTC, xuanyu66 commented on core/src/main/scala/com/pingcap/tispark/auth/TiAuthorization.scala
> +  def authorizeForDelete(
It's better to experiment first on TiDB or MySql

2022-03-30 03:35 UTC, shiyuhang0 commented on core/src/main/scala/com/pingcap/tispark/auth/TiAuthorization.scala
> +  def authorizeForDelete(
SELECT privilege has been checked in TiCatalog.loadTable.

2022-03-30 03:37 UTC, shiyuhang0 commented on core/src/main/scala/com/pingcap/tispark/auth/TiAuthorization.scala
> +  def authorizeForDelete(
See design doc for detail. https://github.com/pingcap/tispark/blob/41cf51cf6012b054e4e3a121540655d306b4adb3/docs/design/2022-03-21-delete-support.md#auth-design

2022-04-01 10:11 UTC, shiyuhang0 commented
/run-all-tests

2022-04-01 10:25 UTC, birdstorm approved these changes
LGTM

2022-04-02 08:50 UTC, xuanyu66 requested changes

2022-04-02 09:50 UTC, xuanyu66 approved these changes

2022-04-06 03:25 UTC, shiyuhang0 commented
/run-all-tests profile=spark-3.1.1

2022-04-06 03:25 UTC, shiyuhang0 commented
/run-all-tests profile=spark-3.1.1

2022-04-06 04:11 UTC, xuanyu66 approved these changes

2022-04-06 04:12 UTC, xuanyu66 commented
LGTM

2022-04-06 05:05 UTC, birdstorm approved these changes
LGTM

2022-04-06 05:35 UTC, sunxiaoguang approved these changes

2022-04-06 05:35 UTC, sunxiaoguang commented
/merge

2022-04-06 05:36 UTC, merged