FIX: ClassCastException when commonHandle with type Timestamp and Date
pingcap/tispark pull request #2319
Opened 2022-05-07 06:33 UTC by xuanyu66

### What problem does this PR solve? 

### What is changed and how it works?

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update the `tidb-ansible` repository
 - Need to be included in the release note

2022-05-07 07:33 UTC, xuanyu66 commented
/cherrypick release-2.5

2022-05-07 07:33 UTC, xuanyu66 commented
/cherrypick release-2.4

2022-05-07 07:57 UTC, birdstorm approved these changes
LGTM

2022-05-07 10:44 UTC, shiyuhang0 approved these changes

2022-05-08 04:48 UTC, shiyuhang0 commented
/run-all-tests

2022-05-09 02:31 UTC, shiyuhang0 commented
@xuanyu66 please fix the fail IT

2022-05-09 02:32 UTC, shiyuhang0 requested changes
@xuanyu66 please fix the fail IT

2022-05-09 09:01 UTC, xuanyu66 commented
/run-all-tests

2022-05-09 09:31 UTC, xuanyu66 commented
/run-all-tests

2022-05-09 10:24 UTC, xuanyu66 commented
/run-all-tests

2022-05-09 11:08 UTC, xuanyu66 commented
/run-all-tests

2022-05-09 11:49 UTC, xuanyu66 commented
/run-all-tests

2022-05-09 13:00 UTC, shiyuhang0 commented on tikv-client/src/main/java/com/pingcap/tikv/key/CommonHandle.java
> +        long milliseconds;
use pattern match may be better
- for Timestamp use getTime() when
- for Long /1000
- for other type throw exception

2022-05-09 15:15 UTC, sunxiaoguang commented
/merge

2022-05-09 15:16 UTC, merged