Fix count push down
pingcap/tispark pull request #2445
Opened 2022-07-07 12:58 UTC by shiyuhang0

### What problem does this PR solve? 
https://github.com/pingcap/tispark/issues/2313

### What is changed and how it works?
 - push down count
 - push down Constant(1) when count(1) or count(*)
 - count(set) will not be pushed down because tikv can't accpect this type.
 - count(col1,col2,...) will not be pushed down because TiKV can't accpect (TIDB not support it)

2022-07-08 03:55 UTC, shiyuhang0 commented
/run-all-tests

2022-07-08 04:28 UTC, shiyuhang0 commented
/run-all-tests

2022-07-08 04:51 UTC, shiyuhang0 commented
/run-all-tests

2022-07-11 03:59 UTC, xuanyu66 requested changes

2022-07-11 03:59 UTC, xuanyu66 commented on core/src/main/scala/org/apache/spark/sql/catalyst/expressions/TiExprUtils.scala
> +          Constant.create(1, null)
Add some code comments

2022-07-12 09:04 UTC, Daemonxiao commented
Could you please add some content about how to solve this bug in "How it works"?

2022-07-13 05:49 UTC, shiyuhang0 commented
> Could you please add some content about how to solve this bug in "How it works"?

done

2022-07-19 07:57 UTC, shiyuhang0 commented
/run-all-tests

2022-07-19 13:13 UTC, xuanyu66 approved these changes

2022-07-20 13:25 UTC, shiyuhang0 commented
/run-all-tests

2022-07-21 03:10 UTC, shiyuhang0 commented
/run-all-tests

2022-07-21 04:04 UTC, shiyuhang0 commented
/run-all-tests tidb=v6.1.0 pd=v6.1.0 tikv=v6.1.0

2022-07-21 05:22 UTC, shiyuhang0 commented
/run-all-tests

2022-07-21 05:36 UTC, shiyuhang0 commented
/run-all-tests

2022-07-21 06:24 UTC, shiyuhang0 commented
/run-all-tests

2022-07-21 06:25 UTC, shiyuhang0 commented
/run-all-tests

2022-07-21 07:49 UTC, shiyuhang0 commented
/run-all-tests

2022-07-21 08:18 UTC, shiyuhang0 commented
/run-all-tests

2022-07-21 09:04 UTC, shiyuhang0 commented
/run-all-tests

2022-07-21 10:28 UTC, shiyuhang0 commented
/run-all-tests

2022-07-22 03:03 UTC, shiyuhang0 commented
/run-all-tests

2022-07-25 03:06 UTC, zhangyangyu commented on core/src/test/scala/org/apache/spark/sql/pushdown/AvePushDownSuite.scala
> +class AvePushDownSuite extends BasePushDownSuite() {
rename to avg plz

2022-07-25 06:48 UTC, zhangyangyu approved these changes

2022-07-25 06:48 UTC, zhangyangyu commented on core/src/test/scala/org/apache/spark/sql/pushdown/AvgPushDownSuite.scala
> +  test("Test - Ave push down pk") {
```suggestion
  test("Test - Avg push down pk") {
```

2022-07-25 06:56 UTC, shiyuhang0 commented
/run-all-tests

2022-07-25 11:07 UTC, xuanyu66 commented
/merge

2022-07-25 11:09 UTC, merged