Only do auth check for tables in TiDB
pingcap/tispark pull request #2489
Opened 2022-08-04 09:14 UTC by TrafalgarRicardoLu

### What problem does this PR solve? 
Only do auth check for tables in TiDB.

### What is changed and how it works?
We will check the catalog name of operation. If it doesn't use `tidb_catalog`, we won't do auth check for it.

### Check List 

Tests 
 - Unit test
 - Integration test

2022-08-08 03:30 UTC, shiyuhang0 commented
It's better to add some test

2022-08-09 03:03 UTC, xuanyu66 requested changes
Add some IT. https://github.com/pingcap/tispark/blob/master/core/src/test/scala/com/pingcap/tispark/auth/TiAuthIntegrationSuite.scala

2022-08-09 07:24 UTC, xuanyu66 commented on core/src/test/scala/com/pingcap/tispark/auth/TiAuthIntegrationSuite.scala
> +  test("Operator on hive table should pass") {
move methods before afterAll()

2022-08-09 07:30 UTC, shiyuhang0 approved these changes

2022-08-09 07:31 UTC, Daemonxiao approved these changes

2022-08-12 06:58 UTC, xuanyu66 approved these changes

2022-08-12 06:58 UTC, xuanyu66 commented
/run-all-tests

2022-08-13 11:39 UTC, shiyuhang0 commented
/merge

2022-08-13 11:40 UTC, merged