bump spark version
pingcap/tispark pull request #2544
Opened 2022-09-15 07:24 UTC by shiyuhang0

### What problem does this PR solve? 
Bump Spark version
- from 3.0.2 to 3.0.3
- from 3.1.1 to 3.1.3
- from 3.2.1 to 3.2.3

This pr is a supplement to https://github.com/pingcap/tispark/pull/2486

2022-09-15 07:46 UTC, shiyuhang0 commented
/run-all-tests

2022-09-15 09:15 UTC, shiyuhang0 commented
/run-all-tests

2022-09-16 02:55 UTC, shiyuhang0 commented
/run-all-tests

2022-09-16 05:31 UTC, shiyuhang0 commented
/run-all-tests profile=spark3.1

2022-09-16 08:15 UTC, shiyuhang0 commented
/run-all-tests profile=spark3.1

2022-09-16 09:43 UTC, zhangyangyu approved these changes

2022-09-16 10:51 UTC, shiyuhang0 commented
/run-all-tests profile=spark3.1

2022-09-17 03:10 UTC, shiyuhang0 commented
/run-all-tests profile=spark3.1

2022-09-19 02:38 UTC, shiyuhang0 commented
/run-all-tests profile=spark3.1

2022-09-19 03:55 UTC, shiyuhang0 commented
/run-all-tests profile=spark3.2

2022-09-19 05:48 UTC, shiyuhang0 commented
/run-all-tests profile=spark3.2

2022-09-19 06:37 UTC, xuanyu66 requested changes
https://github.com/pingcap/tispark/blob/master/pom.xml#L183-L209
Bump these too

2022-09-19 06:38 UTC, xuanyu66 commented
And the better solution is to define variables so that we won't miss the places need to be modified

2022-09-19 06:42 UTC, Daemonxiao approved these changes

2022-09-19 07:53 UTC, shiyuhang0 commented
> https://github.com/pingcap/tispark/blob/master/pom.xml#L183-L209 Bump these too

has done in https://github.com/pingcap/tispark/pull/2486

2022-09-22 05:37 UTC, shiyuhang0 commented
/run-all-tests profile=spark3.2

2022-09-22 05:54 UTC, shiyuhang0 commented
/run-all-tests profile=spark3.2

2022-09-22 05:57 UTC, zhangyangyu commented on pom.xml
>          <spark.version.release>3.0</spark.version.release>
still need or not?

2022-09-22 06:02 UTC, shiyuhang0 commented on pom.xml
>          <spark.version.release>3.0</spark.version.release>
we need it for it is the default value

2022-09-22 06:07 UTC, shiyuhang0 commented on pom.xml
>          <spark.version.release>3.0</spark.version.release>
I have optimized it

2022-09-22 06:07 UTC, shiyuhang0 commented
/run-all-tests profile=spark3.2

2022-09-22 06:13 UTC, xuanyu66 approved these changes

2022-09-22 06:20 UTC, shiyuhang0 commented
/run-all-tests profile=spark3.2

2022-09-22 06:28 UTC, shiyuhang0 commented
/run-all-tests profile=spark3.2

2022-09-22 07:23 UTC, shiyuhang0 commented
/run-all-tests profile=spark3.2

2022-09-22 08:23 UTC, shiyuhang0 commented
/run-all-tests profile=spark3.1

2022-09-22 09:43 UTC, shiyuhang0 commented
/run-all-tests profile=spark3.2

2022-09-22 10:20 UTC, shiyuhang0 commented
/run-all-tests

2022-09-22 12:25 UTC, merged