Enhancement CBO
pingcap/tispark pull request #2563
Opened 2022-10-12 08:23 UTC by shiyuhang0

### What problem does this PR solve? 

After this PR, TiSpark will choose the store according to the cost.

Before this pr, TiSpark usually choose tiflash once the table has tiflash replica.

2022-10-12 08:24 UTC, shiyuhang0 commented
/run-all-tests

2022-10-12 09:21 UTC, Daemonxiao approved these changes

2022-10-12 09:39 UTC, shiyuhang0 commented
/run-all-tests test-flash=true

2022-10-12 12:56 UTC, shiyuhang0 commented
/run-all-tests test-flash=true

2022-10-13 04:47 UTC, shiyuhang0 commented
/run-all-tests

2022-10-13 04:49 UTC, xuanyu66 requested changes

2022-10-13 04:49 UTC, xuanyu66 commented on tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java
> +          TiKVScanPlan minIndexPlan = null;
```suggestion
          TiKVScanPlan minCostIndexPlan = null;
```

2022-10-13 04:49 UTC, xuanyu66 commented on tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java
> +                minIndexPlan = plan;
```suggestion
                minCostIndexPlan = plan;
```

2022-10-13 04:49 UTC, xuanyu66 commented on tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java
> +          if (minIndexPlan != null && (minIndexCost < minCostPlan.getCost() || useIndexScanFirst)) {
```suggestion
          if (minCostIndexPlan != null && (minIndexCost < minCostPlan.getCost() || useIndexScanFirst)) {
```

2022-10-13 05:31 UTC, Daemonxiao commented on tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java
>      // Set DAG Request's store type as minPlan's store type.
```suggestion
    // Set DAG Request's store type as minCostPlan's store type.
```

2022-10-13 05:31 UTC, Daemonxiao commented on tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java
> +    TiStoreType minPlanStoreType = minCostPlan.getStoreType();
```suggestion
    TiStoreType minCostPlanStoreType = minCostPlan.getStoreType();
```

2022-10-13 05:31 UTC, Daemonxiao commented on tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java
>      if (minPlanStoreType == TiStoreType.TiKV
```suggestion
    if (minCostPlanStoreType == TiStoreType.TiKV
```

2022-10-13 05:31 UTC, Daemonxiao commented on tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java
>      dagRequest.setStoreType(minPlanStoreType);
```suggestion
    dagRequest.setStoreType(minCostPlanStoreType);
```

2022-10-14 04:54 UTC, xuanyu66 approved these changes

2022-10-14 04:56 UTC, Daemonxiao approved these changes

2022-10-14 04:57 UTC, shiyuhang0 commented
/merge

2022-10-14 04:57 UTC, merged