Support partition pruning with to_days function
pingcap/tispark pull request #2593
Opened 2022-11-24 10:57 UTC by shiyuhang0

### What problem does this PR solve? 

TiSpark only supports partition pruning with
- column expression
- year (col)

To_DAYS(col) needs to be supported.

The DDL may like this:
```
CREATE TABLE `pt_todays_date` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL,
  `purchased` date DEFAULT NULL,
  index `idx_id`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
PARTITION BY RANGE (to_days(purchased)) (
  PARTITION p0 VALUES LESS THAN (to_days('1995-01-02')),
  PARTITION p1 VALUES LESS THAN (to_days('2000-01-02')),
  PARTITION p2 VALUES LESS THAN (732313),
  PARTITION p3 VALUES LESS THAN (MAXVALUE)
)
```
### What is changed and how it works?

**Support To_DAYS(col)**
1. Alter `Astbuilder` to support convert partExprStr (contains TO_DAYS) to Expression with AstBuilder
2. Add `TO_DAYS` func in `FuncCallExpr` and add the method to deal with to_days in `FuncCallExprEval.java` (calculate the literal in where clause to the result of to_days)
3. Support `TO_DAYS` in `PartAndFilterExprRewriter.java`
4. Enhancement `Converter.java` to support converting int to date and DateTime. So, TiSpark can judge if the filter condition is included in the partition table. (Bad Design, why don't just use int to judge? I just follow the original design)

 
** Fix the bug that year(col) throw exception when col is datetime type**

- Enhancement `FuncCallExprEval.java` to support converting java.sql.Timestamptimestamp(datetime type in TiDB) to datetime
- Enhancement `Converter.java` to support converting int to date and DateTime

2022-11-24 11:00 UTC, shiyuhang0 commented
/run-all-tests tidb=v6.1.0 tikv=v6.1.0

2022-11-24 11:04 UTC, shiyuhang0 commented
/run-all-tests tidb=v6.1.0 tikv=v6.1.0

2022-11-24 13:25 UTC, xuanyu66 requested changes

2022-11-24 13:25 UTC, xuanyu66 commented on tikv-client/src/main/java/com/pingcap/tikv/types/Converter.java
> +        return new ExtendedDateTime(new DateTime((int) val, 1, 1, 0, 0));
add comment to explain what is this value

2022-11-24 13:25 UTC, xuanyu66 commented on tikv-client/src/main/java/com/pingcap/tikv/expression/FuncCallExprEval.java
> +    int var1 = 719528;
change to constant

2022-11-24 14:02 UTC, shiyuhang0 commented
/run-all-tests tidb=v6.1.0 tikv=v6.1.0

2022-11-25 02:32 UTC, zhangyangyu approved these changes

2022-11-25 02:50 UTC, xuanyu66 approved these changes

2022-11-25 02:52 UTC, shiyuhang0 commented
/merge

2022-11-25 02:53 UTC, merged