Fix read from range column partition table error
pingcap/tispark pull request #2639
Opened 2023-03-06 07:44 UTC by shiyuhang0

### What problem does this PR solve? 

close #2638

### What is changed and how it works?

1. Fix the output of explain: TiSpark no more throw `NoSuchElementException` when there is no partition after partition prune.

2. Fix the bug that no partitions will be selected in the range column partition table.

 TiSpark will contain `''` when generates partition exprs. For example, if your DDL is `PARTITION p1 VALUES LESS THAN ('CN001')`, you will get something like `${column_name} less than "'CN001'"`. Then, your filter can not match the partition exprs.

Just Fix this to let tispark generate something like `${column_name} less than "CN001"`.

2023-03-06 07:46 UTC, shiyuhang0 commented
/run-all-tests

2023-03-06 09:43 UTC, shiyuhang0 commented
/run-all-tests

2023-03-13 05:27 UTC, shiyuhang0 commented
/run-all-tests

2023-03-13 09:36 UTC, xuanyu66 requested changes

2023-03-13 09:36 UTC, xuanyu66 commented on tikv-client/src/main/java/com/pingcap/tikv/expression/PartitionPruner.java
> +   * string literal. e.g. 'string' -> "string" '''string''' -> "'string'" 'string''' -> "string'"
`'string''' -> "string'"`  looks strange

2023-03-17 06:43 UTC, Daemonxiao approved these changes

2023-03-17 07:57 UTC, xuanyu66 approved these changes

2023-03-17 07:57 UTC, xuanyu66 commented
/run-all-tests

2023-03-19 13:08 UTC, shiyuhang0 commented
/merge

2023-03-19 13:10 UTC, merged